repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: local
    hooks:
      - id: parameter_docs
        name: parameter_docs
        entry: nf-core schema docs -f -o docs/parameters.md
        language: system
        pass_filenames: false
